React style guide
cthit/style-guides pull request #1
Opened 2018-06-27 12:34 UTC by Portals

This PR is not ready yet. This is a starting point of a React style guide. I have used the Gamma project as a starting point to create this style guide. I am opening this PR to start a discussion on how we should design all React project in the future. 

The goal is to merge this style guide at the end of the summer. By then the common components from Gamma should have been made into a library.

2018-06-27 12:37 UTC, Hultner commented
You do know there's native HR's in markdown, 

---
Like this `---` ^

2018-06-27 12:39 UTC, Portals commented
Did not now, will fix! Thanks!

2018-07-03 08:51 UTC, Portals commented
I have updated my todo list with the following: Always try to use stateless components and that you should write good tests.

2019-07-23 14:03 UTC, Hoidi requested changes

2019-07-23 14:03 UTC, Hoidi commented on react/README.md
> +An element is a stateless and [pure](https://en.wikipedia.org/wiki/Pure_function) component that should only focus on presentational matters. They should take in props, and display it. An element may
Last sentence. It should always what? Is something missing or am I missing something?

2019-07-23 14:03 UTC, Hoidi commented on react/README.md
> +Within the src folder, there should only be three folders. [Common](#common), [Common-ui](#common-ui), [Use-cases](#use-case) and [App](#app).
I count four folder. And what about api?

2019-07-23 14:48 UTC, Portals commented
@Hoidi Resolved your issues

2019-07-23 14:49 UTC, Hoidi approved these changes

2019-07-25 10:42 UTC, Riddarvid approved these changes

2019-07-25 11:06 UTC, Flakt approved these changes

2019-07-25 12:12 UTC, cajoho99 approved these changes

2019-07-25 12:18 UTC, lindskogen approved these changes

2019-07-25 12:22 UTC, Kalior approved these changes

2019-07-26 12:44 UTC, EmElw approved these changes

2019-07-27 18:02 UTC, LatteG approved these changes

2019-07-31 12:34 UTC, merged